openapi: 3.0.0
info:
  description: "API template"
  version: "0.0.0"
  title: "API template"
servers:
  - url: 'http://localhost:3000/'
paths:
  /vols:
    get:
      tags:
        - "Vols"
      summary: "Lister tous les vols possibles"
      parameters:
        - in: query
          name: depart
          required: false
          schema:
            type: string
          description: "Aéroport de départ"
        - in: query
          name: destination
          required: false
          schema:
            type: string
          description: "Aéroport d'arrivée"
    post:
      tags:
        - "Vols"
      summary: "Créer un vol"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                volName:
                  type: string
                dateDepart:
                  type: datetime
                villeDepart:
                  type: string
                villeArrive:
                  type: string
  /vol/{idVol}:
    get:
      tags:
        - "Vols"
      summary: "Consulter un vol spécificique avec son identifiant"
      parameters:
        - name: idVol
          in: path
          required: true
          description: "Identifiant du vol"
          schema:
            type: integer
            format: int64
            minimum: 1
    put:
      tags:
        - "Vols"
      summary: "Editer un vol."
      parameters:
        - name: idVol
          in: path
          required: true
          description: "Identifiant du vol"
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                volName:
                  type: string
                dateDepart:
                  type: datetime
                villeDepart:
                  type: string
                villeArrive:
                  type: string
    delete:
      tags:
        - "Vols"
      summary: "Supprimer un vol"
      parameters:
        - name: idVol
          in: path
          required: true
          description: "Identifiant du vol"
          schema:
            type: integer
            format: int64
            minimum: 1